# Main rules  
title: "Way of knowledge"
remote_theme: pmarsceill/just-the-docs  
color_scheme: dark
search_enabled: false    

# Aux links for the upper right navigation
aux_links:
  "Way of knowledge - Code":
    - "https://github.com/januarythirtyfirst/Way-of-knowledge/tree/main"
    
# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true  
